name: social_media
description: A new Flutter project.


publish_to: 'none' 


version: 2.0.0+2

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  anim_search_bar: ^2.0.3
  cached_network_image: ^3.2.1
  cloud_firestore: ^4.4.4
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  firebase_storage: ^11.0.16
  floating_bottom_bar: ^0.0.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  flutter_snake_navigationbar: ^0.6.1
  get: ^4.6.5
  google_sign_in: ^6.0.2
  image: ^4.0.15
  image_picker: ^0.8.7
  intl: null
  intl_phone_field: ^3.1.0
  otp_text_field: ^1.1.3
  pandabar: ^0.1.2
  path_provider: ^2.0.14
  permission_handler_windows: ^0.1.2
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  uuid: ^3.0.7
  webview_flutter: ^4.0.5
  zego_uikit_signaling_plugin:
  zego_uikit_prebuilt_call: 
  
 
dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0
flutter_icons:  
  android: "launcher_icon"
  ios: true
  image_path: "lib/precentation/assets/amjoz-low-resolution-color-logo.png"
  flutter_test:
    sdk: flutter

flutter:

 
  uses-material-design: true
  assets:
    - lib/precentation/assets/
  #   - images/a_dot_ham.jpeg
  
  